version: '3.9'

services:

  master:
    build: 
      context: ./
      target: ros_base
    container_name: ros-master
    ports:
      - "11311:11311"
      - "33690:33690"
    environment:
      - "ROS_IP=172.19.0.2"
    command: stdbuf -o L roscore
    networks:
      ros:
        ipv4_address: 172.19.0.2

  talker:
    build: 
      context: ./
      target: ros_base
    container_name: ros-talker
    depends_on:
      - master
    environment:
      - "ROS_MASTER_URI=http://172.19.0.2:11311"
      - "ROS_IP=172.19.0.3"
    command: stdbuf -o L rostopic pub /chatter std_msgs/String "hello" -r 1
    networks:
      ros:
        ipv4_address: 172.19.0.3

  listener:
    build: 
      context: ./
      target: ros_base
    container_name: ros-listener
    depends_on:
      - master
    environment:
      - "ROS_MASTER_URI=http://172.19.0.2:11311"
      - "ROS_IP=172.19.0.4"
    command: stdbuf -o L rostopic echo /chatter
    networks:
      ros:
        ipv4_address: 172.19.0.4

  dev:
    build: 
      context: ./
      target: ros_dev
    container_name: ros-dev
    depends_on:
      - master
    environment:
      - "ROS_MASTER_URI=http://172.19.0.2:11311"
      - "ROS_IP=172.19.0.5"
    ports:
      - "6080:6080"
    # extra_hosts:
    #   - "$MASTER_HOSTNAME:$MASTER_IP"
    # cap_add:
    #   - "NET_ADMIN"
    #   - "NET_BROADCAST"
    volumes:
      - ./workspaces/:/workspaces/
    command: bash -c "/start_novnc.sh"
    networks:
      ros:
        ipv4_address: 172.19.0.5

networks:
  ros:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.19.0.0/24
        gateway: 172.19.0.1
